# Generated by Django 5.0.3 on 2024-04-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billings',
            options={'verbose_name': 'Facturacion', 'verbose_name_plural': 'Facturacion'},
        ),
        migrations.AlterModelOptions(
            name='historicalbillings',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Facturacion', 'verbose_name_plural': 'historical Facturacion'},
        ),
    ]
