# Generated by Django 5.0.3 on 2024-04-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_alter_historicalinventorydetails_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventorydetails',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventorydetails',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
