# Generated by Django 4.2 on 2024-08-12 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generic_tables', '0005_alter_options_icon'),
        ('inventories', '0003_historicalinventorydetails_is_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinventories',
            name='inventory_status',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='generic_tables.attributes'),
        ),
        migrations.AddField(
            model_name='inventories',
            name='inventory_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='generic_tables.attributes'),
            preserve_default=False,
        ),
    ]
