# Generated by Django 5.0.3 on 2024-04-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_tables', '0004_alter_options_icon_alter_options_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='icono'),
        ),
    ]
