# Generated by Django 5.0.3 on 2024-04-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_tables', '0003_options_menus_historicalmenus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='icon',
            field=models.CharField(max_length=50, null=True, verbose_name='icono'),
        ),
        migrations.AlterField(
            model_name='options',
            name='link',
            field=models.CharField(max_length=50, null=True, verbose_name='link'),
        ),
    ]
