# Generated by Django 5.0.3 on 2024-04-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventorydetails',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Cantidad del producto'),
        ),
        migrations.AlterField(
            model_name='inventorydetails',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Cantidad del producto'),
        ),
    ]
